[ERROR]	2025-07-21T08:08:43.267Z	b5a73434-e736-4398-a5d6-4582dcf6434e	Failed to ingest document
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 99, in lambda_handler
    response = agent_client.ingest_knowledge_base_documents(
        knowledgeBaseId=KB_ID,
        dataSourceId=DATA_SOURCE_ID,
        documents=documents
    )
  File "/var/lang/lib/python3.13/site-packages/botocore/client.py", line 598, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.13/site-packages/botocore/context.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/var/lang/lib/python3.13/site-packages/botocore/client.py", line 1018, in _make_api_call
    request_dict = self._convert_to_request_dict(
        api_params=api_params,
    ...<3 lines>...
        headers=additional_headers,
    )
  File "/var/lang/lib/python3.13/site-packages/botocore/client.py", line 1085, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
        api_params, operation_model
    )
  File "/var/lang/lib/python3.13/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter documents[0].content, value: NIN: 78-669 30
