[ERROR] KeyError: 'NHS1I2TLDX'
Traceback (most recent call last):
  File "/var/lang/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 21, in <module>
    KB_ID = os.environ["NHS1I2TLDX"]           # The Bedrock Knowledge Base ARN or ID
  File "<frozen os>", line 717, in __getitem__
INIT_REPORT Init Duration: 979.73 ms	Phase: init	Status: error	Error Type: Runtime.Unknown
